### ISSUE TITLE
doesn't work

### ISSUE THREAD

**Issue by luntik2012** [andrepolischuk/keep#25]
Eats 70Mb of RAM and doesn't work. No notes, strange white space on the left side, some icons are invalid.
![screenshot from 2017-11-15 12-51-43](https://user-images.githubusercontent.com/8270543/32829706-e96ece36-ca03-11e7-9da4-717f49d50161.png)

**Comment by andrepolischuk** [comment]
@luntik2012 sorry for silence, what os do you use?

**Comment by luntik2012** [comment]
Also, my 1-line home-written qt-app for single-page google keep eats ~19mb RAM. And I have qt in my repos, and it's faster, and it works, and there are many apps using it. So why do you develop this app?

**Comment by andrepolischuk** [comment]
it's running in ubuntu 15.04 x64

<img width="919" alt="screen shot 2017-12-21 at 14 01 54" src="https://user-images.githubusercontent.com/8956796/34253184-99fc944e-e657-11e7-8ccc-db143be9518f.png">

**Comment by andrepolischuk** [comment]
1. you can try use packaged application instead of build from sources, download it here https://github.com/andrepolischuk/keep/releases/latest/.
2. installation error in arch was throw because npm couldn't resolve npm registry url. it can be because you have a proxy in your os.
3. I wrote this app on electron, because I didn't know qt and I wanted try electron for desktop apps. writing this app on javascript/electron was easier for me.

**Comment by pigsflew** [comment]
Andre, i feel like you should close this issue; as the built app does work on all platforms. If a user is unable to get it to build for them, and they're building it from sources, they ought to be versed enough in code and their OS to provide a more detailed bug report.

that point about qt is complete garbage unless the user puts their own app into github with full cross-platform support the way yours is. QT does run on Windows and Mac, but it requires a secondary install, and is more memory intensive, not less. This is also true of Linux computers that are not built on QT, such as any GTK+ based Desktop Environment (like Ubuntu, for instance)
