### ISSUE TITLE
high memory consumption

### ISSUE THREAD

**Issue by ags799** [andrepolischuk/keep#29]
Running this app starts two processes on my machine:
1. `Keep`, which uses ~40 MB
2. `Keep Helper`, which uses ~270 MB

This seems like a lot of memory for a notetaking app. It's more than Google Chrome consumes, even with a Keep tab open.

**Comment by andrepolischuk** [comment]
I have 60 and 230 MB on my machine for notes. But when I run not authorized app I have 60 for Keep and 40MB for Keep helper.

It turns out that the keep notes web application itself uses a lot of memory. For example, I run it in Chrome, see tab Google Keep and subframe on the following screenshot:

![image](https://user-images.githubusercontent.com/8956796/38138086-6ea9967a-3431-11e8-8bd3-3e4243ea5e8e.png)

**Comment by ags799** [comment]
I see, thanks for the explanation. I didn't take a look at the tab memory. Guess there's not much we can do.
